FROM python:3

MAINTANER Mohammad Alasawedah

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && \
     apt-get install -y --no-install-recommends \
         gdal-bin \
         libgdal-dev \
    #     python3-opencv && \
    mkdir -p \
        data/input/chips/images \
        data/input/chips/fields \
        data/input/checkpoint \
        data/output && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
    
ENTRYPOINT [ "bash", "run-model.sh" ]
